Algoritmo "QUESTAO05"
// Disciplina :Lógica de Programação
//Fazer um programa que pergunte o salário de um funcionário e
// apresente este salário com um aumento de 15%.
Var
// Seção de Declarações das variáveis 
 salar: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval("Qual o seu salário: ")
  leia(salar)
  Escreval("O seu salário será (com aumento de 15%): ", salar * 1.5 ,"reais")
Fimalgoritmo